version: '3'

services:
  hugo:
    build: .
    image: maliceio/docs:${VERSION:-latest}
    restart: always
    volumes:
      - .:/docs  
    ports:
      - '80:80'
    environment:
      MALICE_DOCS_THEME: "hugo-material-docs"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  # https-portal:
  #   depends_on:
  #     - hugo
  #   image: steveltn/https-portal:1
  #   restart: always
  #   ports:
  #     - '80:80'
  #     - '443:443'
  #   links:
  #     - hugo
  #   environment:
  #     DOMAINS: 'malice.io-> http://hugo'
  #     STAGE: 'production'
  #     FORCE_RENEW: 'true'
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "200k"
  #       max-file: "10"
