version: 2
jobs:
  build:
    working_directory: /docs
    docker:
      - image: docker:17.07.0-ce-git
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/docs.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/docs.tar | true
      - run:
          name: Build docs Docker image
          command: |
            docker version
            docker build --cache-from=docs -t docs .
            docker image list docs
      - run:
          name: Get Docker image size
          command: |
            mkdir /tmp/artifacts;
            docker images --format "{{.Size}}" docs > /tmp/artifacts/size;
      - store_artifacts:
          path: /tmp/artifacts
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/docs.tar docs
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/docs.tar
      - run:
          name: Run tests
          command: |
            docker run -d --name docs docs
            docker run --network container:docs appropriate/curl --retry 10 --retry-connrefused http://localhost:443
