version: 2
jobs:
  build:
    working_directory: /docs
    docker:
      - image: docker:17.06.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py2-pip=9.0.1-r1 curl=7.54.0-r0
            pip install \
              docker-compose==1.14.0 \
              awscli==1.11.112
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.05.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/docs.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/docs.tar | true
      - run:
          name: Build docslication Docker image
          command: |
            docker version
            docker build --cache-from=docs -t docs .
            docker image list docs
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/docs.tar docs
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/docs.tar
      - run:
          name: Run tests
          command: |
            docker run -d --name docs docs
            docker run --network container:docs appropriate/curl --retry 10 --retry-connrefused http://localhost
      # - deploy:
      #     name: Push docslication Docker image
      #     command: |
      #       if [ "${CIRCLE_BRANCH}" == "master" ]; then
      #         login="$(aws ecr get-login)"
      #         ${login}
      #         docker tag docs "${ECR_ENDPOINT}/docs:${CIRCLE_SHA1}"
      #         docker push "${ECR_ENDPOINT}/docs:${CIRCLE_SHA1}"
      #       fi
